server:
  port : 9999
zuul:
  routes:
    offer:
      path: /offer/**
      url: http://54.165.84.232:1001/api/v1
    shoe:
      path: /shoe/**
      url: http://54.165.84.232:1002/api/v1
    wishlist:
      path: /wishlist/**
      url: http://54.165.84.232:1003
    cart:
      path: /cart/**
      url: http://54.165.84.232:1004/api/v1
